# -*- coding: utf-8 -*-
"""코드 연습4 _코드연습 3 수정 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w-bNnbYKqh59wEhNpmBF3Mhceo4_CMt1
"""

from tensorflow.keras.layers import Input, Dense
from tensorflow.keras import Model

from sklearn.datasets import load_breast_cancer

from sklearn.model_selection import train_test_split

cancer = load_breast_cancer()

x_feat = cancer['data']
y_target = cancer['target'].reshape(-1, 1)

x_train, x_test, y_train, y_test = train_test_split(x_feat, y_target, test_size = 0.2)

"""#여기!"""

#이름 부여
xInput = Input(batch_shape = (None, x_train.shape[1]), name = "In")
hLayer = Dense(10, name = 'hidden_1')(xInput)
for i in range(4):
  hLayer = Dense(10, name = 'hidden_'+str(i+2))(hLayer)

yOutput = Dense(y_train.shape[1], activation = "sigmoid", name = 'Out')(hLayer)

model = Model(xInput, yOutput)

model.compile(loss = 'binary_crossentropy', optimizer = 'adam')

model.summary()

"""---"""

model = Model(xInput, yOutput)

model.compile(loss = 'binary_crossentropy', optimizer = 'adam')

model.fit(x_train, y_train, epochs = 100)

y_prob = model.predict(x_test)

y_pred = (y_prob>0.5).astype('int8')

acc = (y_test == y_pred).sum()/y_test.shape[0]
acc = (y_test == y_pred).mean()
print(acc)

