# -*- coding: utf-8 -*-
"""코드연습7 - 당뇨병 데이터.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X6Y-w7xFKhHd6klCp8RssOWcAuRxw-6M
"""

import numpy as np
import pandas as pd

path = '/content/drive/MyDrive/Colab Notebooks/data/'
diabetes = pd.read_csv(path + 'diabetes.csv')
diabetes.head()

x_feat = np.array(diabetes.drop('Outcome', axis=1))
y_target = np.array(diabetes['Outcome']).reshape(-1,1)

#데이터 쪼개기
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_feat, y_target, test_size=0.2)

#입력층, 은닉층, 출력층 구성할 때 사용
from tensorflow.keras.layers import Input, Dense
#모델 구성할 때 사용
from tensorflow.keras.models import Model

x_train.shape[1]

y_train.shape[1]

#Network 생성
#입력층 구성
xInput = Input(batch_shape = (None, x_train.shape[1]))

#은닉층 구성
#activation = relu
hLayer = Dense(10, activation = 'relu')(xInput)

#출력층 구성
yOutput = Dense(y_train.shape[1], activation='sigmoid')(hLayer)

#모델을 만든다
model = Model(xInput, yOutput)

#학습 방법을 설정
model.compile(loss = 'binary_crossentropy', optimizer='adam')

#학습시킨다
model.fit(x_train, y_train, epochs = 100)

#평가
y_prob = model.predict(x_test)
y_pred = (y_prob>0.5).astype('int8')

acc = (y_test == y_pred).mean()
print(acc)