# -*- coding: utf-8 -*-
"""SVR(연습).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12jmanwNAciGcXeEzLFezz3YDhvuK3mxh
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

x = np.arange(1, 19).reshape(-1, 1)
y = np.array([4.14, 3.37, 11.7, 6.3, 10.25, 10.32, 
              5.67, 7.12, 12.47, 17.97, 19.34, 21.62, 
              15.64, 25.83, 29.28, 21.47, 26.3, 32.48])

# 기본 코드
# model = SVR(kernel='rbf', gamma=0.1, C=2.0)
model = SVR(kernel='linear', C=2.0)
model.fit(x, y)
y_hat = model.predict(x)

# 추정된 y를 시각화 한다.
plt.scatter(x, y, c='red', s=100, alpha=0.7)
plt.plot(x, y_hat, marker='o', c='blue', alpha=0.7)
plt.show()

